version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlepass
    volumes:
      - db_data:/var/lib/mysql

  moodle:
    image: moodlehq/moodle-php-apache:8.3
    container_name: moodle-web
    restart: always
    ports:
      - "8080:80"
    environment:
      PHP_INI-upload_max_filesize: 200M
      PHP_INI-post_max_size: 210M
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - db

volumes:
  db_data:
